### ISSUE TITLE
Doesn't look to work with RG300 Bright Screen

### ISSUE THREAD

**Issue by Taywee** [retrofw/firmware#11]
Flashing it to the card gives me a blank screen.  [The version for the RG-300 V3 IPS here](https://jutleys.wixsite.com/retrogamers97-90/post/rg-350-v1-0-firmware-release) works fine (I know the site looks sketchy, but it's what is officially recommended by retrogame).  The version it works with is the RG-300 V3 IPS.

I'm running on Linux, and basically what I've done is this (with `/dev/sdh` being my card):

```sh
$ sh RG-300_bright_screen.bat
$ sudo dd if=RetroFW.img of=/dev/sdh
```

**Comment by pingflood** [comment]
RetroFW v2.0 is out and if your device has an IPS LCD module you have to use the Type 5B firmware.

Check the release notes, instructions and download the RetroFW v2.0 here:
https://github.com/retrofw/firmware/releases/tag/2.0

**Comment by Taywee** [comment]
That did the job!  Thank you so much.
