### ISSUE TITLE
cannot use fba

### ISSUE THREAD

**Issue by xplangchao** [retrofw/firmware#12]
handheld console: RS-97 Plus, 2nd anniversary version with IPS panel.
fw version: 2.0
FBA version: downloaded here, opk file.
issue: cannot play any game including cps1, cps2 and others.

**Comment by prophet69** [comment]
Same for me:
Type RetroFW 3B
NES ok, SNES ok, MD ok.
FBA A320, FBA GCW0 an GnGeo not a single ROM works...

**Comment by maskmark** [comment]
rs-07 same.

**Comment by pingflood** [comment]
We are inspecting an issue with FAT32 partition mounting flags that could cause such problem.

If you could, please test these patches:

https://drive.google.com/drive/folders/1hkUu80bJ5gHhfmlwvcOHLW7okK8_1XIg?usp=sharing

To apply the patch, copy the IPK files to your device and browse to it using the GMenuNX Explorer.
It will apply the patch and system will reboot in a few seconds.

Test the issue right after the reboot.

Please report back if it solves the issue and which patch has the best results for you:

**Comment by maskmark** [comment]
vfat_mixed works for firmware_4B ( retro arcade mini rs-07) .
fba and gngeo can browse and load roms on internal sdcard.
and gpsp can load gba_bios in its own folder now.

**Comment by pingflood** [comment]
Ok, thanks!

We had some more reports in our Discord channel and it seems the vfat_lower is working better.

We will release a fixed version soon
