### ISSUE TITLE
the newly supported rs-07 doesn't have a power button to apply hotkey actions.

### ISSUE THREAD

**Issue by maskmark** [retrofw/firmware#13]
thx for the new cfw witch supports rs-07,  the retro arcade mini. however, as it doesn't have a click.power button, it cannot trigger  ingame menu，or system combo key. will u please manage to resolve that? thank you.

**Comment by pingflood** [comment]
Most of the OPS ports made by the RetroFW team were updated to support Select + Start as menu.

But we don't have control over emulators and ports from different developers.

So, when you find an issue like that, the best solution is to open an issue in the developer's GitHub.

**Comment by maskmark** [comment]
> Most of the OPK ports made by the RetroFW team were updated to support Select + Start as menu.
> 
> But we don't have control over emulators and ports from different developers.
> 
> So, when you find an issue like that, the best solution is to open an issue in the developer's GitHub.

good,that's right.but how about combo keys for retrofw 2.0 itself,like power+start to kill current app or press power  3 sec for in-game pause menu. is there or will there be a workaround? thank you.

**Comment by pingflood** [comment]
Unfortunately the lack of buttons is a hardware flaw.

We are not planning any other workaround about this subject at this moment, but your suggestion is noted.
