### ISSUE TITLE
MPLAYER App?

### ISSUE THREAD

**Issue by joeydm** [retrofw/firmware#14]
Was the MPLAYER App removed from this version? I just recently got it to work in trhe previous RFW version and when I updated to this latest version I see it is not included,

Any way to get the app back?

**Comment by pingflood** [comment]
RetroFW never included any app or emulator.

Our philosophy is to share a lightweight and clean image. It's up to the user add and customize their devices at their will.

If you ever used a RetroFW that had any app or emulator included, it was probably customized and re-imaged by users.

Our focus is on the core features. Apps like mplayer are built by other developers. We suggest you to look at Dingoonity forums, our Discord server and the firmware GitHub.
