### ISSUE TITLE
fba emus start+select will trigger Player2's start

### ISSUE THREAD

**Issue by tytannial** [retrofw/firmware#6]
It's a Unibios using problem.

**Comment by tytannial** [comment]
![20190615235506](https://user-images.githubusercontent.com/11215623/59553565-12e97900-8fc9-11e9-8a60-5921405d8f33.png)
I have looked up the source code, weird defualt keymap and no config for it.

**Comment by pingflood** [comment]
The RetroFW v2.0 FBA-A320 has updated key combos.

Now:
Select + Start: Menu
Select + X: Service Menu
Select + Y: Show/hide FPS
Select + B: Player 2 start
Select + L: Quick load state
Select + R: Quick save state
